### ISSUE TITLE
Add variable interpolation support for repos

### ISSUE THREAD

**Issue by msrb** [konflux-ci/rpm-lockfile-prototype#36]
Variable interpolation support for `repofiles` was implemented in https://github.com/konflux-ci/rpm-lockfile-prototype/pull/27. This works, but the need for git credentials seems to be problematic (see: CWFHEALTH-3323).

There is also one (hypothetical) limitation:

Let's consider the following example:

- We have a base image: `ubi`
- We have a layered image 1: `layered-1`
  - We are able to read the repo file from the `ubi` git repo
- We have a leaf image that uses `layered-1` as the base image: `leaf-1`
  - git repo of the parent image doesn't have any repo file

So, to make this work, we would need to maintain the repo file in both `ubi` and `layered-1` repositories.

# Proposal

I think that having the variable interpolation option in the `repos` section could help with both of these problems (credentials + distance from root).

I imagine that it could work like this (just an example, I don't insist on this format):

```
  repos:
    # List of objects with repoid and baseurl
    - varsFromContainerfile: Containerfile
    - repoid: rhel
      baseurl: https://example.com/rhel/nightly/rhel/{compose-id}/compose/BaseOS/$basearch/os/
   ...
```

In the base image (`ubi`), we would create a label `compose-id`, that would be then inherited to all layered images.

WDYT?
